//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movy()
        {
            this.show_times = new HashSet<show_times>();
            this.actors = new HashSet<actor>();
            this.genres = new HashSet<genre>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string image { get; set; }
        public Nullable<int> id_director { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<double> star { get; set; }
        public Nullable<int> old { get; set; }
        public string type { get; set; }
        public string trailer { get; set; }
        public string thumbnail { get; set; }
    
        public virtual director director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<show_times> show_times { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor> actors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genre> genres { get; set; }
    }
}
