//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class problem
    {
        public int id { get; set; }
        public int id_staff { get; set; }
        public string status { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<decimal> expense { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
