//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_RCP_Entities : DbContext
    {
        public QL_RCP_Entities()
            : base("name=QL_RCP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actors { get; set; }
        public virtual DbSet<director> directors { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<foods_drinks> foods_drinks { get; set; }
        public virtual DbSet<movy> movies { get; set; }
        public virtual DbSet<problem> problems { get; set; }
        public virtual DbSet<screen_rooms> screen_rooms { get; set; }
        public virtual DbSet<screen_rooms_seats> screen_rooms_seats { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<show_times> show_times { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transactions_foods_drinks> transactions_foods_drinks { get; set; }
        public virtual DbSet<voucher_uses> voucher_uses { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
    }
}
