//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class screen_rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public screen_rooms()
        {
            this.screen_rooms_seats = new HashSet<screen_rooms_seats>();
            this.show_times = new HashSet<show_times>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_cinema { get; set; }
        public string name { get; set; }
        public Nullable<int> amount_seats { get; set; }
    
        public virtual cinema cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<screen_rooms_seats> screen_rooms_seats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<show_times> show_times { get; set; }
    }
}
