//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class screen_rooms_seats
    {
        public int id_screen_room { get; set; }
        public int id_seat { get; set; }
        public string status { get; set; }
    
        public virtual screen_rooms screen_rooms { get; set; }
        public virtual seat seat { get; set; }
    }
}
