//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaction()
        {
            this.transactions_foods_drinks = new HashSet<transactions_foods_drinks>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public Nullable<int> id_staff { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> time_transaction { get; set; }
        public string type_transaction { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual staff staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions_foods_drinks> transactions_foods_drinks { get; set; }
        public virtual ticket ticket { get; set; }
    }
}
