//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMA_BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions_foods_drinks
    {
        public int id_transaction { get; set; }
        public int id_food_drink { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual foods_drinks foods_drinks { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
